// ══════════════════════════════════════════════════════════════════════════
// DONNÉES CULTURELLES — 14 RÉGIONS / ETHNIES DE CÔTE D'IVOIRE
// ══════════════════════════════════════════════════════════════════════════

export const REGIONS = {
  'Savanes': {
    color: '#C0392B',
    gradient: 'linear-gradient(135deg, #7b1a1a, #C0392B)',
    ethnies: ['Sénoufo', 'Malinké', 'Lobi'],
    capitale: 'Korhogo',
    population: '1 364 000',
    zone: 'Nord',
    desc: "Terre des forgerons sacrés et des tisserands d'exception. La société Poro structure la vie sociale Sénoufo depuis des millénaires.",
    img: 'https://picsum.photos/seed/savanes-korhogo/800/500',
  },
  'Denguélé': {
    color: '#8E44AD',
    gradient: 'linear-gradient(135deg, #4a1a6e, #8E44AD)',
    ethnies: ['Malinké', 'Dioula', 'Senadi'],
    capitale: 'Odienné',
    population: '273 000',
    zone: 'Nord-Ouest',
    desc: "Carrefour des cultures mandingues, terre de commerçants et de griotsaux voix millénaires. Frontière naturelle avec la Guinée.",
    img: 'https://picsum.photos/seed/dengue-odienne/800/500',
  },
  'Zanzan': {
    color: '#D35400',
    gradient: 'linear-gradient(135deg, #7a2e00, #D35400)',
    ethnies: ['Lobi', 'Koulango', 'Abron'],
    capitale: 'Bondoukou',
    population: '876 000',
    zone: 'Nord-Est',
    desc: "Région orientale aux traditions animistes profondes. Les Lobi, architectes de tatas impressionnantes, gardent des rituels initiatiques parmi les plus secrets d'Afrique.",
    img: 'https://picsum.photos/seed/zanzan-bondoukou/800/500',
  },
  'Woroba': {
    color: '#16A085',
    gradient: 'linear-gradient(135deg, #0a5a4a, #16A085)',
    ethnies: ['Worodougou', 'Malinké', 'Tagwana'],
    capitale: 'Séguéla',
    population: '540 000',
    zone: 'Centre-Ouest',
    desc: "Terre de transition entre savane et forêt. Les Worodougou, commerçants itinérants, ont tissé des réseaux d'échanges dès le XVIe siècle.",
    img: 'https://picsum.photos/seed/woroba-seguela/800/500',
  },
  'Montagnes': {
    color: '#27AE60',
    gradient: 'linear-gradient(135deg, #145c33, #27AE60)',
    ethnies: ['Dan (Yacouba)', 'Guéré', 'Wobé', 'Toura'],
    capitale: 'Man',
    population: '1 200 000',
    zone: 'Ouest',
    desc: "Pays des masques qui courent sur l'eau et des danseurs de feu. Les Dan ont produit certains des masques les plus célèbres au monde. Terre de forêts denses et de cascades sacrées.",
    img: 'https://picsum.photos/seed/montagnes-man/800/500',
  },
  'Bas-Sassandra': {
    color: '#2980B9',
    gradient: 'linear-gradient(135deg, #14446e, #2980B9)',
    ethnies: ['Bété', 'Dida', 'Neyo', 'Bakwé'],
    capitale: 'San-Pédro',
    population: '1 590 000',
    zone: 'Sud-Ouest',
    desc: "Littoral forestier, terre des pêcheurs Neyo et des cultivateurs de cacao. Les Bété, guerriers et danseurs, ont longtemps résisté à la colonisation.",
    img: 'https://picsum.photos/seed/bassassandra-sanpedro/800/500',
  },
  'Sassandra-Marahoué': {
    color: '#F39C12',
    gradient: 'linear-gradient(135deg, #7a4e06, #F39C12)',
    ethnies: ['Bété', 'Guro', 'Gouro'],
    capitale: 'Daloa',
    population: '1 090 000',
    zone: 'Centre-Ouest',
    desc: "Entre fleuve Sassandra et forêt, pays des sculpteurs Guro dont les masques Zamble et Gu figurent dans tous les grands musées du monde.",
    img: 'https://picsum.photos/seed/sassandra-daloa/800/500',
  },
  'Vallée du Bandama': {
    color: '#E74C3C',
    gradient: 'linear-gradient(135deg, #7a1e1e, #E74C3C)',
    ethnies: ['Baoulé', "N'Gban", 'Faafouè'],
    capitale: 'Bouaké',
    population: '1 470 000',
    zone: 'Centre',
    desc: "Cœur du peuple Baoulé, artisans d'exception. La reine Aura Poku a fondé ce peuple en sacrifice. Leurs statuettes «blolo bian» et masques Goli sont admirés mondialement.",
    img: 'https://picsum.photos/seed/bandama-bouake/800/500',
  },
  'Lacs': {
    color: '#1ABC9C',
    gradient: 'linear-gradient(135deg, #0a6b5c, #1ABC9C)',
    ethnies: ['Baoulé', 'Attié', 'Abidji'],
    capitale: 'Dimbokro',
    population: '950 000',
    zone: 'Centre-Est',
    desc: "Région lacustre du centre-est, confluent de plusieurs peuples Akan aux structures royales sophistiquées et aux rites de l'eau profondément ancrés.",
    img: 'https://picsum.photos/seed/lacs-dimbokro/800/500',
  },
  'Yamoussoukro': {
    color: '#7D6608',
    gradient: 'linear-gradient(135deg, #3d3204, #7D6608)',
    ethnies: ['Baoulé', "N'Gban"],
    capitale: 'Yamoussoukro',
    population: '355 000',
    zone: 'Centre',
    desc: "Village natal de Félix Houphouët-Boigny, devenu capitale politique. Les N'Gban Baoulé gardent les traditions royales du fondateur de la nation.",
    img: 'https://picsum.photos/seed/yamoussoukro/800/500',
  },
  'Gôh-Djiboua': {
    color: '#117A65',
    gradient: 'linear-gradient(135deg, #073d32, #117A65)',
    ethnies: ['Guro', 'Bété', 'Dida'],
    capitale: 'Gagnoa',
    population: '800 000',
    zone: 'Centre-Ouest',
    desc: "Pays des masques Guro et de la société initiatique Gla. Les Bété de Gagnoa ont produit des figures politiques majeures de la Côte d'Ivoire.",
    img: 'https://picsum.photos/seed/goh-gagnoa/800/500',
  },
  'Lagunes': {
    color: '#2C3E50',
    gradient: 'linear-gradient(135deg, #111e2b, #2C3E50)',
    ethnies: ['Avikam', 'Adjoukrou', 'Alladian', 'Abidji'],
    capitale: 'Dabou',
    population: '830 000',
    zone: 'Sud',
    desc: "Peuples des lagunes côtières aux rites initiatiques Dipri redoutables. Les Adjoukrou pratiquent encore la montée aux palmiers ritualisée lors du Dipri de Gomon.",
    img: 'https://picsum.photos/seed/lagunes-dabou/800/500',
  },
  'Abidjan': {
    color: '#6C3483',
    gradient: 'linear-gradient(135deg, #330d42, #6C3483)',
    ethnies: ['Ébrié', 'Dioula', 'Pluriethnique'],
    capitale: 'Abidjan',
    population: '5 000 000',
    zone: 'Sud',
    desc: "Les Ébrié, maîtres autochtones du Plateau, accueillent depuis un siècle des migrants de 60+ nations. Abidjan est le creuset de l'identité ivoirienne moderne et le centre du Coupé-Décalé.",
    img: 'https://picsum.photos/seed/abidjan-plateau/800/500',
  },
  'Comoé': {
    color: '#B7950B',
    gradient: 'linear-gradient(135deg, #5c4a06, #B7950B)',
    ethnies: ['Agni', 'Attié', 'Abron', 'Koulango'],
    capitale: 'Abengourou',
    population: '1 070 000',
    zone: 'Est',
    desc: "Royaume des Agni Sanwi, peuple Akan à la structure royale sophistiquée. Le chef du Sanwi porte encore aujourd'hui les insignes royaux en or massif hérités du XVIIIe siècle.",
    img: 'https://picsum.photos/seed/comoe-abengourou/800/500',
  },
};

export const CULTURAL_PILLARS = [
  {
    id: 'architecture',
    icon: '🏛️',
    label: 'Architecture & Habitat',
    sublabel: "L'art de bâtir en harmonie avec la terre et le climat",
    color: '#C0392B',
  },
  {
    id: 'gastronomie',
    icon: '🍲',
    label: 'Gastronomie & Cuisine',
    sublabel: "Les saveurs ancestrales, fermentation et interdits alimentaires",
    color: '#E67E22',
  },
  {
    id: 'masques',
    icon: '🎭',
    label: 'Masques, Danses & Arts Sacrés',
    sublabel: "Le pont mystique entre le monde des vivants et celui des esprits",
    color: '#8E44AD',
  },
  {
    id: 'textiles',
    icon: '🧵',
    label: 'Textiles, Parures & Vêtements',
    sublabel: "Du Pagne Kita au Tapa d'écorce, le langage du corps",
    color: '#D4AC0D',
  },
  {
    id: 'oral',
    icon: '🗣️',
    label: 'Sources Orales & Proverbes',
    sublabel: "La bibliothèque vivante transmise par la parole",
    color: '#27AE60',
  },
  {
    id: 'rites',
    icon: '📅',
    label: 'Rites & Grandes Célébrations',
    sublabel: "Le calendrier des fêtes, initiations et réjouissances",
    color: '#E74C3C',
  },
  {
    id: 'musique',
    icon: '🎶',
    label: 'Rythmes, Musiques & Instruments',
    sublabel: "Du Balafon aux Tambours parleurs, la pulsation du pays",
    color: '#16A085',
  },
  {
    id: 'social',
    icon: '🤝',
    label: 'Organisation Sociale & Alliances',
    sublabel: "Parenté, royauté et pacte du Toukpè",
    color: '#2980B9',
  },
  {
    id: 'bijoux',
    icon: '💍',
    label: 'Esthétique, Bijoux & Signes',
    sublabel: "L'art de l'or, les perles et scarifications symboliques",
    color: '#F39C12',
  },
  {
    id: 'pharmacopee',
    icon: '🌿',
    label: 'Pharmacopée & Savoirs Anciens',
    sublabel: "La science des plantes, forêts sacrées et médecine traditionnelle",
    color: '#1ABC9C',
  },
];

export const QUICK_PROMPTS = [
  { emoji: '💃', label: 'Nord + Danse', prompt: "Je viens du Nord de la Côte d'Ivoire et je m'intéresse à la danse traditionnelle. Génère-moi un parcours culturel immersif complet." },
  { emoji: '🎭', label: 'Masques Sacrés Ouest', prompt: "Génère un parcours immersif sur les masques sacrés des peuples Dan, Guéré et Wobé de l'Ouest ivoirien." },
  { emoji: '👑', label: 'Royauté Agni', prompt: "Crée un parcours sur la royauté et les traditions des Agni du Sanwi, leurs insignes royaux en or et leur organisation politique." },
  { emoji: '🌊', label: 'Peuples Lagunaires', prompt: "Parcours immersif sur les rites initiatiques Dipri des peuples lagunaires du Sud de la Côte d'Ivoire." },
  { emoji: '🎵', label: 'Musique Baoulé', prompt: "Génère un parcours musical complet sur les instruments, rythmes et chants traditionnels du peuple Baoulé." },
  { emoji: '🌿', label: 'Pharmacopée Sénoufo', prompt: "Parcours sur la pharmacopée, les forêts sacrées et les savoirs médicinaux des anciens Sénoufo du Nord." },
  { emoji: '🍲', label: 'Gastronomie du Sud', prompt: "Parcours culinaire immersif sur les traditions gastronomiques ancestrales des peuples Ébrié et Adjoukrou du Sud." },
  { emoji: '🏛️', label: 'Architecture Lobi', prompt: "Parcours sur l'architecture des tatas Lobi de la région du Zanzan, leurs techniques de construction et significations rituelles." },
];